package com.chatapp;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class MessageTest {

    private static final String RECIPIENT_1 = "+27718693002";
    private static final String MESSAGE_1 = "Hi Mike, can you join us for dinner tonight?";
    private static final String RECIPIENT_2 = "08575975889";
    private static final String MESSAGE_2 = "Hi Keegan, did you receive the payment?";

    @TempDir
    Path tempDir;

    private Path jsonFile;

    @BeforeEach
    void setUp() {
        Message.resetAll();
        jsonFile = tempDir.resolve("storedMessages.json");
        Message.setStorageFile(jsonFile.toString());
    }

    // ---------- assertEquals tests ----------

    @Test
    void messageLengthSuccess() {
        assertEquals("Message ready to send.", Message.checkMessageLength(MESSAGE_1));
        assertEquals("Message ready to send.", Message.checkMessageLength("a".repeat(250)));
    }

    @Test
    void messageLengthFailure() {
        assertEquals("Message exceeds 250 characters by 10; please reduce the size.",
                Message.checkMessageLength("a".repeat(260)));
    }

    @Test
    void recipientCorrectlyFormatted() {
        Message message = new Message(RECIPIENT_1, MESSAGE_1);
        assertEquals("Cell phone number successfully captured.", message.checkRecipientCell());
    }

    @Test
    void recipientIncorrectlyFormatted() {
        Message message = new Message(RECIPIENT_2, MESSAGE_2);
        assertEquals("Cell phone number is incorrectly formatted or does not contain an international code. "
                + "Please correct the number and try again.", message.checkRecipientCell());
    }

    @Test
    void messageHashTestCase1() {
        Message message = new Message("0012345678", 0, RECIPIENT_1, MESSAGE_1);
        assertEquals("00:0:HITONIGHT", message.createMessageHash());
        assertEquals("00:0:HITONIGHT", message.getMessageHash());
    }

    @Test
    void messageHashesInLoop() {
        // {message ID, message number, message text, expected hash}
        String[][] data = {
            {"0012345678", "0", MESSAGE_1, "00:0:HITONIGHT"},
            {"0087654321", "1", MESSAGE_2, "00:1:HIPAYMENT"},
            {"5599999999", "2", "Thanks", "55:2:THANKSTHANKS"},
            {"1234567890", "3", "Call me when you get this!", "12:3:CALLTHIS"}
        };
        for (String[] row : data) {
            Message message = new Message(row[0], Integer.parseInt(row[1]), RECIPIENT_1, row[2]);
            assertEquals(row[3], message.createMessageHash());
        }
    }

    @Test
    void autoGeneratedMessageNumbersAppearInHash() {
        Message first = new Message(RECIPIENT_1, MESSAGE_1);
        Message second = new Message(RECIPIENT_2, MESSAGE_2);
        assertTrue(first.getMessageHash().endsWith(":0:HITONIGHT"));
        assertTrue(second.getMessageHash().endsWith(":1:HIPAYMENT"));
    }

    @Test
    void messageIDCreated() {
        Message message = new Message(RECIPIENT_1, MESSAGE_1);
        assertTrue(message.getMessageID().matches("\\d{10}"));
        assertEquals("Message ID generated: " + message.getMessageID(), message.getMessageIDMessage());
    }

    @Test
    void messageSentSend() {
        Message message = new Message(RECIPIENT_1, MESSAGE_1);
        assertEquals("Message successfully sent.", message.SentMessage(1));
    }

    @Test
    void messageSentDisregard() {
        Message message = new Message(RECIPIENT_2, MESSAGE_2);
        assertEquals("Press 0 to delete the message.", message.SentMessage(2));
    }

    @Test
    void messageSentStore() throws IOException {
        Message message = new Message(RECIPIENT_1, MESSAGE_1);
        assertEquals("Message successfully stored.", message.SentMessage(3));

        String json = Files.readString(jsonFile);
        assertTrue(json.contains("\"recipient\": \"" + RECIPIENT_1 + "\""));
        assertTrue(json.contains("\"message\": \"" + MESSAGE_1 + "\""));
        assertTrue(json.contains("\"messageHash\": \"" + message.getMessageHash() + "\""));
    }

    // ---------- assertTrue / assertFalse / totals ----------

    @Test
    void messageIDLengthCheck() {
        assertTrue(new Message("1234567890", 0, RECIPIENT_1, MESSAGE_1).checkMessageID());
        assertFalse(new Message("12345678901", 0, RECIPIENT_1, MESSAGE_1).checkMessageID());
    }

    @Test
    void totalMessagesSentCountsOnlySentMessages() {
        Message first = new Message(RECIPIENT_1, MESSAGE_1);
        Message second = new Message(RECIPIENT_2, MESSAGE_2);

        first.SentMessage(1);   // Test case 1: select Send
        second.SentMessage(2);  // Test case 2: select Discard

        assertEquals(1, Message.returnTotalMessages());
    }

    @Test
    void printMessagesShowsOnlySentMessages() {
        Message first = new Message(RECIPIENT_1, MESSAGE_1);
        Message second = new Message(RECIPIENT_2, MESSAGE_2);
        first.SentMessage(1);
        second.SentMessage(2);

        String printed = Message.printMessages();
        assertTrue(printed.contains(MESSAGE_1));
        assertTrue(printed.contains(RECIPIENT_1));
        assertFalse(printed.contains(MESSAGE_2));
    }
}
